# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45d815e255d44b1bff347d018b2b0efad1ad61a81009c57a67e2292697ec9c199e7131771ccf01fab827fe7ce348db02d9c25318083a5f78289e37b2410f449b

test:
  secret_key_base: 2561d82bade6cdc43cb7d18f4ecd5b85ba9309966ae6eb6b0519db3d72adf4660fd168ded7f7790737341d26861314ec8ad83dcb765c512fca4478ec21f611da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
